name: videogame
description: Flutter VideoGame

version: 2.7.4+64

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  #photo_view: ^0.11.1
  rxdart: ^0.27.0
  firebase_core: ^2.1.1
  firebase_analytics: ^10.0.4
  google_mobile_ads: ^2.0.1
  firebase_messaging: ^14.0.4
#  flutter_staggered_grid_view: ^0.6.2
  dio: ^4.0.0
  dio_smart_retry: ^1.3.2
#  dio_http_cache: ^0.3.0
  cached_network_image: ^3.0.0
  fluttertoast: ^8.0.3
  intro_views_flutter: ^3.0.0
  share: ^2.0.1
  path_provider: ^2.0.5
  like_button: ^2.0.2
  package_info: ^2.0.0
  #  app_review: ^1.1.0+1
  launch_review: ^3.0.1
  url_launcher: ^6.0.12
  #  google_fonts: ^1.1.1
  permission_handler: ^10.2.0
  #  archive: ^3.1.2
  #  flutter_package_manager: ^0.2.0
  shared_preferences: ^2.0.8
  sqflite:
  path: ^1.8.2
  event_bus: ^2.0.0
  in_app_purchase: ^3.0.8
#    path: ../videogame-lib/plugins/packages/in_app_purchase/in_app_purchase
  flutter_local_notifications: ^12.0.3
  #  wiredash: ^0.6.2
  firebase_crashlytics: ^3.0.4
  material_floating_search_bar: ^0.3.4
  games_services: ^3.0.0
  google_sign_in: ^5.2.1
  #  app_review: ^2.1.1+1
  flutter_signin_button: ^2.0.0
  google_api_availability: ^3.0.1
  flutter_archive: ^5.0.0
  device_info: ^2.0.2
  #  flutter_fgbg: ^0.2.0
  wakelock: ^0.6.1+2
  intl_utils: ^2.6.1
  animated_text_kit: ^4.2.2
  shimmer_animation: ^2.1.0
  sliver_tools: ^0.2.8
  dynamic_height_grid_view: ^0.0.3
  firebase_remote_config: ^3.0.7
#  google_fonts: ^2.3.2
#  f_logs: ^2.0.0
#  flutter_email_sender: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
  localizely:
    project_id: 2011cc41-53e1-48ce-b1da-c75a4e9c8097
